version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: api_image_backend
    logging:
      options:
        max-size: 250m
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Moscow
      - SERVER_ADDRESS=0.0.0.0:8000
      - SERVER_PORT=8000
      - POSTGRES_CONN=postgresql+asyncpg://postgres:postgres@localhost:5432/test
      - POSTGRES_JDBC_URL=jdbc:postgresql://localhost:5432/test
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=test
      - RANDOM_SECRET=secret
    ports:
      - "8000:8000"
    command: python src/app.py
    restart: unless-stopped

volumes:
  postgres_data:
