version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: api_image_backend
    logging:
      options:
        max-size: 250m
    volumes:
      - .:/app
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Moscow
      - RANDOM_SECRET=secret
      - PORT=8000
      - HOST=0.0.0.0
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    command: python app.py
    restart: unless-stopped

volumes:
  postgres_data:
